[package]
name = "ProjectEulerRust"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license="MIT"
readme = "README.md"
repository = "https://github.com/gifnksm/ProjectEulerRust"
keywords = ["algebra", "algorithms", "computation", "mathematics", "numerics"]
description = "Solving Project Euler with Rust lang."

[lib]
name = "common"

[dependencies]
curl = "*"
itertools = "*"
glob = "*"
generic-matrix = "*"
getopts = "*"
num = "*"
polynomial = "*"
rustc-serialize = "*"
term = "*"
time = "*"
union-find = "*"
topological-sort = "*"
enum_primitive = "*"

[dev-dependencies]
rand = "*"

[dependencies.cont_frac]
path = "./pkg/cont_frac"

[dependencies.integer]
path = "./pkg/integer"

[dependencies.iter]
path = "./pkg/iter"

[dependencies.playing_card]
path = "./pkg/playing_card"

[dependencies.prime]
path = "./pkg/prime"

[dependencies.seq]
path = "./pkg/seq"
